name: event_logger
version: 0.0.1
author: Brandon White <jennexproject+eventlogger@gmail.com>
description: Helper package for recording event logs.
homepage: http://jennex.it/
environment:
  sdk: '>=1.12.0 <2.0.0'